apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myd
  name: myd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myd

  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: myd
    spec:
      containers:
      - image: rohitraut3366/apache-webserver-php:v2
        name: apache-webserver-php
