apiVersion: v1
kind: Pod
metadata:
    name: mypod
    labels:
       loc: india
       team: team1
spec:
    containers:
        - name: mycontainer
          image: rohitraut3366/apache-webserver-php

