apiVersion: v1
kind: PersistentVolume
metadata:
    name: mypvw
    labels:
       class: standard
       app: web
spec:
    storageClassName: ""
    capacity: 
       storage: 10Gi
    accessModes:
         - ReadWriteOnce
    hostPath:
         path: /data
    persistentVolumeReclaimPolicy: Delete
