apiVersion: v1
kind: Pod
metadata:
    name: mysql-secret
    labels:
        app: backend
spec:
    containers:
       - image: mysql:5.7
         name: wp-mysql
         env:
           - name: MYSQL_ROOT_PASSWORD
             valueFrom:
                 secretKeyRef:
                       name: wp-mysql
                       key: rootpass
           - name: MYSQL_USER
             valueFrom:
                 secretKeyRef:
                       name: wp-mysql
                       key: username
           - name: MYSQL_PASSWORD
             valueFrom:
                 secretKeyRef:
                       name: wp-mysql
                       key: userpass
           - name: MYSQL_DATABASE
             value: mydb
