apiVersion: apps/v1
kind: Deployment
metadata:
    name: myd
spec:
    replicas: 3
    selector:
        matchLabels:
             env: prod
        matchExpressions:
             - { key: team, operator: In, values: ["team1"] }
    template:
         metadata:
             labels:
                env: prod
                team: team1
         spec:
            containers:
                - name: mc
                  image: vimal13/apache-webserver-php
