apiVersion: v1
kind: Pod
metadata: 
   name: wordpress-mysql
   labels:
       loc: in
       app: web
spec:
    containers:
        - image: mysql:5.7
          name: mysql-con
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "3366"
            - name: MYSQL_DATABASE
              value: mydb
            - name: MYSQL_USER
              value: rohit
            - name: MYSQL_PASSWORD
              value: "3366"       
